import type { Locale } from "@/i18n/config";
type L = { "es-CL": string; en: string }; const l = (es: string, en: string): L => ({ "es-CL": es, en });

export const survia = {
  id: "survia-price-the-route", version: "1.0.0",
  title: l("Survia — Define el precio de la ruta", "Survia — Price the Route"),
  subtitle: l("Una decisión de mercado bajo capacidad ociosa, costos crecientes y entrada competitiva.", "A market decision under spare capacity, rising costs and competitive entry."),
  role: l("Eres responsable de recomendar la arquitectura de tarifas para la ruta Puerto Norte–Valle Central antes de la entrada de VíaSur.", "You must recommend the fare architecture for the Puerto Norte–Valle Central route before VíaSur enters."),
  stages: [l("Mercado", "Market"), l("Economía", "Economics"), l("Recomendación inicial", "Initial recommendation"), l("Respuesta competitiva", "Competitor response"), l("Incentivo", "Incentive wrinkle"), l("Recomendación final", "Final recommendation"), l("Resultado", "Result")],
  market: {
    title: l("Primero, define las preguntas", "Start by defining the questions"),
    body: l("Survia tiene demanda alta los fines de semana, baja utilización de martes a jueves y dos segmentos con flexibilidad distinta. Un operador de menor costo entrará el próximo trimestre.", "Survia has strong weekend demand, low Tuesday–Thursday utilization and two segments with different flexibility. A lower-cost operator enters next quarter."),
    questions: [l("¿El cambio observado es una respuesta al precio o un desplazamiento de demanda?", "Is the observed change a price response or a demand shift?"), l("¿Dónde existe capacidad ociosa y dónde aparece el siguiente salto?", "Where is capacity spare and where does the next step occur?"), l("¿Qué sustitutos y restricciones tiene cada segmento?", "Which substitutes and constraints does each segment face?"), l("¿Cómo puede responder el entrante?", "How can the entrant respond?")],
    metrics: [[l("Utilización fin de semana", "Weekend utilization"), "91%"], [l("Utilización martes–jueves", "Tuesday–Thursday utilization"), "54%"], [l("Viajeros flexibles", "Flexible travelers"), "46%"], [l("Viajeros con horario fijo", "Schedule-bound travelers"), "54%"]] as [L, string][],
    prompt: l("Elige las tres preguntas económicas que investigarías antes de recomendar.", "Choose the three economic questions you would investigate before recommending."),
  },
  economics: {
    title: l("La economía cambia por salida", "Economics changes by departure"),
    body: l("El costo medio de toda la ruta no decide si conviene llenar un asiento vacío. La próxima salida adicional sí crea un salto de costo.", "The route-wide average cost does not decide whether to fill an empty seat. The next additional departure does create a cost step."),
    metrics: [[l("Tarifa promedio", "Average fare"), "$24.800"], [l("Costo incremental por pasajero", "Incremental cost per passenger"), "$6.200"], [l("Nueva salida", "Additional departure"), "$1,85M"], [l("Elasticidad flexible", "Flexible segment elasticity"), "1,55"], [l("Elasticidad horario fijo", "Schedule-bound elasticity"), "0,42"], [l("Alza costo de combustible", "Fuel cost increase"), "+14%"]] as [L, string][],
    prompt: l("Explica qué costos son relevantes para una salida con asientos libres y qué cambia cuando se agota la capacidad.", "Explain which costs matter for a departure with empty seats and what changes when capacity is exhausted."),
  },
  choices: [l("Aumentar todas las tarifas 12%", "Raise all fares 12%"), l("Bajar valle y subir punta", "Lower off-peak and raise peak"), l("Igualar la tarifa baja del entrante", "Match the entrant's low headline fare"), l("Mantener precios y reducir frecuencia", "Hold prices and reduce frequency"), l("Tarifas segmentadas con restricciones", "Segmented fares with restrictions")],
  initial: { title: l("Formula una tesis inicial", "Form an initial thesis"), prompt: l("Recomienda una opción. Conecta demanda, margen, elasticidad y estructura de mercado; declara un riesgo y el dato que podría cambiar tu decisión.", "Recommend an option. Connect demand, margin, elasticity and market structure; state one risk and the evidence that could change your decision.") },
  competitor: { title: l("El rival no responde igual en toda la ruta", "The rival does not respond equally across the route"), body: l("VíaSur anuncia que igualará promociones seleccionadas de martes a jueves, pero sólo dispone de capacidad para dos salidas diarias y no puede ampliar la oferta en horarios punta durante seis meses.", "VíaSur announces it will match selected Tuesday–Thursday promotions, but only has capacity for two daily departures and cannot expand peak supply for six months."), prompt: l("¿Defiendes o revisas tu recomendación? Anticipa la mejor respuesta de VíaSur y explica por qué.", "Do you defend or revise your recommendation? Anticipate VíaSur's best response and explain why.") },
  incentive: { title: l("La evidencia de ventas tiene un incentivo escondido", "Sales evidence has a hidden incentive"), body: l("Los gerentes comerciales reciben bonos por pasajeros transportados, no por contribución. En el canal de agencias, los descuentos fuera de política subieron de 6% a 19% de las ventas.", "Sales managers are paid for passengers carried, not contribution. In the agency channel, off-policy discounting rose from 6% to 19% of sales."), prompt: l("Explica cómo este incentivo distorsiona el comportamiento o la evidencia y qué cambiarías en la política.", "Explain how this incentive distorts behavior or evidence and what you would change in the policy.") },
  final: { title: l("Cierra la decisión", "Close the decision"), prompt: l("Entrega una recomendación ejecutiva final. Incluye arquitectura de tarifas, mecanismo económico, respuesta competitiva, cambio de incentivos y una condición observable de revisión.", "Deliver a final executive recommendation. Include fare architecture, economic mechanism, competitive response, incentive change and an observable review condition."), uncertainty: l("¿Cuál es la incertidumbre que más podría cambiar la decisión?", "Which uncertainty could most change the decision?") },
};

export const surviaCopy = {
  "es-CL": { back: "Volver a la unidad", restart: "Reiniciar", checkpoint: "Checkpoint 01", time: "18 minutos", continue: "Continuar", selected: "seleccionadas", selectThree: "Selecciona exactamente tres preguntas.", responseLong: "Desarrolla la respuesta con al menos 80 caracteres.", selectDecision: "Selecciona una recomendación.", submit: "Enviar recomendación", revise: "Procesar nueva información", finish: "Evaluar decisión", evidence: "Evidencia liberada", dimensions: "Dimensiones evaluadas", strength: "Fortaleza", improvement: "Próximo foco", trajectory: "Trayectoria de decisión", mastery: "Cambios de dominio", map: "Ver cambios en Tu Skala", unit: "Volver a la unidad", result: "Evaluación completada", evaluator: "Evaluación determinística de respaldo", status: "Checkpoint completado" },
  en: { back: "Back to unit", restart: "Restart", checkpoint: "Checkpoint 01", time: "18 minutes", continue: "Continue", selected: "selected", selectThree: "Select exactly three questions.", responseLong: "Develop the response with at least 80 characters.", selectDecision: "Select a recommendation.", submit: "Submit recommendation", revise: "Process new information", finish: "Evaluate decision", evidence: "Evidence released", dimensions: "Dimensions evaluated", strength: "Strength", improvement: "Next focus", trajectory: "Decision trajectory", mastery: "Mastery changes", map: "See changes in Your Skala", unit: "Back to unit", result: "Evaluation complete", evaluator: "Deterministic fallback evaluation", status: "Checkpoint completed" },
};

export const surviaDimensionNames = {
  economicFraming: l("Marco económico", "Economic framing"), marginalReasoning: l("Razonamiento marginal", "Marginal reasoning"), elasticity: l("Elasticidad", "Elasticity"), incentives: l("Incentivos", "Incentives"), marketStructure: l("Estructura de mercado", "Market structure"), strategicInteraction: l("Interacción estratégica", "Strategic interaction"), decisionCoherence: l("Coherencia de decisión", "Decision coherence"), adaptability: l("Adaptabilidad", "Adaptability"),
};
export function st(value: L, locale: Locale) { return value[locale]; }

