"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowIcon, SparkIcon } from "@/components/layout/icons";
import { aiCopilotEconomicsCase, caseDimensionOrder, getAICopilotCaseCopy } from "@/content/cases/ai-copilot-economics";
import { seedEvidence } from "@/content/mastery/seed";
import { useI18n } from "@/i18n/provider";
import { challengeCaseDecision, evaluateCaseDecision } from "@/lib/ai/cases";
import { trackCaseEvent } from "@/lib/analytics/cases";
import { caseStages, aiCopilotCaseStorageKey, createAICopilotCaseSession, nextCaseStage, parseAICopilotCaseSession, type AICopilotCaseSession } from "@/lib/cases/session";
import type { CaseDecision, CaseStage } from "@/lib/cases/schemas";
import { loadGraph } from "@/lib/content/load-content";
import { buildMasteryMap } from "@/lib/demo/state";
import { calculateMastery, type EvidenceEvent } from "@/lib/mastery/engine";
import { useSkalaState } from "@/lib/state/provider";

type CaseBlockProps = {
  session: AICopilotCaseSession;
  update: (patch: Partial<AICopilotCaseSession>, advance?: boolean) => void;
  error: string;
  setError: (value: string) => void;
};

const decisions: CaseDecision[] = ["vendor", "build", "hybrid", "defer"];
const local = <T extends Record<"es-CL" | "en", string>>(value: T, locale: "es-CL" | "en") => value[locale];

function DecisionPicker({ value, onChange }: { value?: CaseDecision; onChange: (decision: CaseDecision) => void }) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale);
  return <div className="case-decision-picker">{decisions.map((decision) => <button type="button" key={decision} className={value === decision ? "selected" : ""} onClick={() => onChange(decision)}>{c.decisions[decision]}</button>)}</div>;
}

function IntroBlock({ update }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const definition = aiCopilotEconomicsCase;
  return <section className="case-opening"><p className="section-label"><SparkIcon />{c.intro.eyebrow}</p><p className="case-opening-code">{c.meta.caseCode} · {definition.estimatedMinutes} {c.meta.minutesShort}</p><h1>{local(definition.title, locale)}</h1><p className="case-opening-subtitle">{local(definition.subtitle, locale)}</p><div className="case-role"><span>{c.intro.youAre}</span><strong>{local(definition.context.role, locale)}</strong><p>{local(definition.context.premise, locale)}</p></div><small>{c.intro.synthetic}</small><button className="primary-action case-action" onClick={() => { trackCaseEvent("case_started", { caseId: definition.id, version: definition.version, locale }); update({ evidenceViewed: [definition.sections[0].id] }, true); }}>{c.intro.enter}<ArrowIcon /></button></section>;
}

function EvidenceBlock({ session, update }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const [active, setActive] = useState(session.evidenceViewed.at(-1) ?? aiCopilotEconomicsCase.sections[0].id);
  const section = aiCopilotEconomicsCase.sections.find((item) => item.id === active)!;
  const select = (id: string) => { setActive(id); if (!session.evidenceViewed.includes(id)) { trackCaseEvent("case_evidence_viewed", { caseId: session.caseId, sectionId: id, locale }); update({ evidenceViewed: [...session.evidenceViewed, id] }); } };
  return <section className="case-workspace-block"><div className="case-block-heading"><p className="eyebrow">{c.evidence.eyebrow}</p><h1>{c.evidence.title}</h1><p>{c.evidence.body}</p></div><div className="case-evidence-tabs" role="tablist">{aiCopilotEconomicsCase.sections.map((item) => <button type="button" role="tab" aria-selected={active === item.id} className={active === item.id ? "active" : ""} key={item.id} onClick={() => select(item.id)}><span>{session.evidenceViewed.includes(item.id) ? c.evidence.viewed : c.evidence.unread}</span>{local(item.label, locale)}</button>)}</div><article className="case-evidence-panel" role="tabpanel"><p className="eyebrow">{local(section.label, locale)}</p><h2>{local(section.title, locale)}</h2><p>{local(section.body, locale)}</p><div className="case-metrics">{section.metrics.map((metric) => <div key={local(metric.label, locale)}><span>{local(metric.label, locale)}</span><strong>{metric.value}</strong><small>{local(metric.note, locale)}</small></div>)}</div></article><p className="case-requirement">{c.evidence.requirement}</p><button className="primary-action case-action" disabled={session.evidenceViewed.length < 4} onClick={() => update({}, true)}>{c.evidence.continue}<ArrowIcon /></button></section>;
}

function InitialDecisionBlock({ session, update, error, setError }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const [decision, setDecision] = useState(session.initialDecision); const [rationale, setRationale] = useState(session.initialRationale ?? ""); const [selected, setSelected] = useState<string[]>(session.citedEvidence ?? []); const [risk, setRisk] = useState(session.primaryRisk ?? ""); const [busy, setBusy] = useState(false);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!decision) return setError(c.errors.decision); if (rationale.trim().length < 70) return setError(c.errors.rationale); if (selected.length < 2) return setError(c.errors.evidence); if (risk.trim().length < 25) return setError(c.errors.risk); setError(""); setBusy(true); const challenge = await challengeCaseDecision({ locale, caseId: session.caseId, caseVersion: session.version, decision, rationale: rationale.trim(), citedEvidence: selected, primaryRisk: risk.trim() }); trackCaseEvent("case_decision_submitted", { caseId: session.caseId, locale, decision }); update({ initialDecision: decision, initialRationale: rationale.trim(), citedEvidence: selected, primaryRisk: risk.trim(), challenge }, true); setBusy(false); };
  return <section className="case-form-block"><p className="eyebrow">{c.initial.eyebrow}</p><h1>{c.initial.title}</h1><p className="case-lede">{c.initial.body}</p><form onSubmit={submit}><h2>{c.initial.prompt}</h2><DecisionPicker value={decision} onChange={setDecision} /><label>{c.initial.rationale}<textarea rows={5} value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder={c.initial.rationalePlaceholder} /></label><fieldset className="case-evidence-select"><legend>{c.initial.evidencePrompt}</legend>{aiCopilotEconomicsCase.sections.map((section) => <label key={section.id}><input type="checkbox" checked={selected.includes(section.id)} onChange={() => toggle(section.id)} /><span>{local(section.label, locale)}</span></label>)}</fieldset><label>{c.initial.risk}<textarea rows={3} value={risk} onChange={(event) => setRisk(event.target.value)} placeholder={c.initial.riskPlaceholder} /></label>{error && <p className="learning-error">{error}</p>}<button className="primary-action case-action" disabled={busy}>{c.initial.submit}<ArrowIcon /></button></form></section>;
}

function ChallengeBlock({ session, update, error, setError }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const [response, setResponse] = useState(session.challengeResponse ?? "");
  const submit = (event: FormEvent) => { event.preventDefault(); if (response.trim().length < 55) return setError(c.errors.challenge); setError(""); trackCaseEvent("case_challenge_answered", { caseId: session.caseId, locale, challengeType: session.challenge!.type }); update({ challengeResponse: response.trim() }, true); };
  return <section className="case-challenge-block"><p className="section-label"><SparkIcon />{c.challenge.eyebrow}</p><h1>{c.challenge.title}</h1><p>{c.challenge.context}</p><blockquote>{session.challenge && local(session.challenge.prompt, locale)}</blockquote><form onSubmit={submit}><textarea aria-label={c.challenge.placeholder} rows={5} value={response} onChange={(event) => setResponse(event.target.value)} placeholder={c.challenge.placeholder} />{error && <p className="learning-error">{error}</p>}<button className="primary-action case-action">{c.challenge.submit}<ArrowIcon /></button></form></section>;
}

function NewInformationBlock({ session, update }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const info = aiCopilotEconomicsCase.newInformation[session.challenge!.newInformationId];
  return <section className="case-new-info"><p className="eyebrow">{c.newInfo.eyebrow}</p><h1>{c.newInfo.title}</h1><article><span>+</span><h2>{local(info.title, locale)}</h2><p>{local(info.body, locale)}</p><strong>{local(info.implication, locale)}</strong></article><p>{c.newInfo.notCorrection}</p><button className="primary-action case-action" onClick={() => update({ newInformationAcknowledged: true }, true)}>{c.newInfo.continue}<ArrowIcon /></button></section>;
}

function RevisionBlock({ session, update, error, setError }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const [decision, setDecision] = useState(session.finalDecision ?? session.initialDecision); const [rationale, setRationale] = useState(session.revisedRationale ?? "");
  const submit = (event: FormEvent) => { event.preventDefault(); if (!decision) return setError(c.errors.decision); if (rationale.trim().length < 80) return setError(c.errors.revision); setError(""); trackCaseEvent("case_revision_submitted", { caseId: session.caseId, locale, changed: decision !== session.initialDecision }); update({ finalDecision: decision, revisedRationale: rationale.trim() }, true); };
  return <section className="case-form-block"><p className="eyebrow">{c.revision.eyebrow}</p><h1>{c.revision.title}</h1><p className="case-lede">{c.revision.body}</p><form onSubmit={submit}><DecisionPicker value={decision} onChange={setDecision} /><label>{c.revision.rationale}<textarea rows={5} value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder={c.revision.placeholder} /></label>{error && <p className="learning-error">{error}</p>}<button className="primary-action case-action">{c.revision.submit}<ArrowIcon /></button></form></section>;
}

function FinalRecommendationBlock({ session, update, error, setError }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const { evidence, addEvidence, completeCase } = useSkalaState(); const [recommendation, setRecommendation] = useState(session.recommendation ?? ""); const [trigger, setTrigger] = useState(session.reviewTrigger ?? ""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (recommendation.trim().length < 100) return setError(c.errors.recommendation); if (trigger.trim().length < 35) return setError(c.errors.trigger); setError(""); setBusy(true); const evaluation = await evaluateCaseDecision({ locale, caseId: session.caseId, caseVersion: session.version, decision: session.initialDecision!, rationale: session.initialRationale!, citedEvidence: session.citedEvidence!, primaryRisk: session.primaryRisk!, challenge: session.challenge!, challengeResponse: session.challengeResponse!, finalDecision: session.finalDecision!, revisedRationale: session.revisedRationale!, recommendation: recommendation.trim(), reviewTrigger: trigger.trim() }); const occurredAt = new Date().toISOString(); const numericDimensions = Object.fromEntries(Object.entries(evaluation.dimensions).map(([name, value]) => [name, value.score])); const caseEvents: EvidenceEvent[] = evaluation.skillEvidence.map((item, index) => ({ id: `${session.sessionId}:${item.skillId}`, skillId: item.skillId, type: "case", performance: item.performance, occurredAt: new Date(Date.now() + index).toISOString(), sourceId: session.sessionId, dimensions: Object.fromEntries(item.dimensions.map((name) => [name, numericDimensions[name]])), metadata: { initialDecision: session.initialDecision, finalDecision: session.finalDecision, challengeType: session.challenge!.type, rationaleSummary: recommendation.trim().slice(0, 180), evaluatorVersion: evaluation.evaluatorVersion, caseId: session.caseId, caseVersion: session.version, trajectory: local(evaluation.trajectory, locale) } })); const nextLedger = [...seedEvidence, ...evidence, ...caseEvents]; const masteryAfter = Object.fromEntries(evaluation.skillEvidence.map((item) => [item.skillId, calculateMastery(item.skillId, nextLedger).mastery])); addEvidence(caseEvents); completeCase({ caseId: session.caseId, sessionId: session.sessionId, completedAt: occurredAt, version: session.version, initialDecision: session.initialDecision!, finalDecision: session.finalDecision!, overallPerformance: evaluation.overallPerformance }); trackCaseEvent("case_completed", { caseId: session.caseId, locale, performance: evaluation.overallPerformance }); trackCaseEvent("case_mastery_updated", { caseId: session.caseId, locale, evidenceCount: caseEvents.length }); update({ recommendation: recommendation.trim(), reviewTrigger: trigger.trim(), evaluation, masteryAfter, completedAt: occurredAt }, true); setBusy(false); };
  return <section className="case-form-block case-final-block"><p className="eyebrow">{c.final.eyebrow}</p><h1>{c.final.title}</h1><p className="case-lede">{c.final.body}</p><form onSubmit={submit}><label>{c.final.recommendation}<textarea rows={6} value={recommendation} onChange={(event) => setRecommendation(event.target.value)} placeholder={c.final.recommendationPlaceholder} /></label><label>{c.final.trigger}<textarea rows={3} value={trigger} onChange={(event) => setTrigger(event.target.value)} placeholder={c.final.triggerPlaceholder} /></label>{error && <p className="learning-error">{error}</p>}<button className="primary-action case-action" disabled={busy}>{busy ? c.final.evaluating : c.final.submit}<ArrowIcon /></button></form></section>;
}

function ResultBlock({ session }: CaseBlockProps) {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const router = useRouter(); const graph = useMemo(() => loadGraph(locale), [locale]); const evaluation = session.evaluation!; const focusSkill = evaluation.skillEvidence.reduce((best, item) => ((session.masteryAfter?.[item.skillId] ?? 0) - (session.masteryBefore[item.skillId] ?? 0)) > ((session.masteryAfter?.[best.skillId] ?? 0) - (session.masteryBefore[best.skillId] ?? 0)) ? item : best).skillId;
  return <section className="case-result"><p className="section-label"><SparkIcon />{c.result.eyebrow}</p><h1>{c.result.title}</h1><div className="case-overall"><span>{c.result.overall}</span><strong>{Math.round(evaluation.overallPerformance * 100)}</strong></div><div className="case-dimension-grid">{caseDimensionOrder.map((dimension) => <article key={dimension}><div><span>{c.dimensions[dimension]}</span><strong>{Math.round(evaluation.dimensions[dimension].score * 100)}</strong></div><i><b style={{ width: `${evaluation.dimensions[dimension].score * 100}%` }} /></i><p>{local(evaluation.dimensions[dimension].reason, locale)}</p></article>)}</div><div className="case-feedback"><article><span>{c.result.strength}</span><p>{local(evaluation.strength, locale)}</p></article><article><span>{c.result.improvement}</span><p>{local(evaluation.improvement, locale)}</p></article></div><div className="case-trajectory"><span>{c.result.trajectory}</span><p><strong>{c.decisions[session.initialDecision!]}</strong><i>→</i><strong>{c.decisions[session.finalDecision!]}</strong></p><small>{local(evaluation.trajectory, locale)}</small></div><section className="case-evidence-result"><p className="eyebrow">{c.result.evidence}</p>{evaluation.skillEvidence.map((item) => { const node = graph.nodes.find((candidate) => candidate.id === item.skillId); const before = session.masteryBefore[item.skillId] ?? 0; const after = session.masteryAfter?.[item.skillId] ?? before; return <div key={item.skillId}><span>{node?.title ?? item.skillId}</span><small>{c.result.mastery}</small><strong>{before}<i>→</i>{after}</strong></div>; })}</section><p className="completion-distinction">{c.result.distinction}</p><div className="case-result-actions"><button className="primary-action" onClick={() => router.push(`/skala?focus=${encodeURIComponent(focusSkill)}&updated=1`)}>{c.result.openGraph}<ArrowIcon /></button><Link className="text-action" href="/cases">{c.result.backCases}</Link></div></section>;
}

const registry: Record<CaseStage, React.ComponentType<CaseBlockProps>> = { intro: IntroBlock, evidence: EvidenceBlock, initial_decision: InitialDecisionBlock, challenge: ChallengeBlock, new_information: NewInformationBlock, revision: RevisionBlock, final_recommendation: FinalRecommendationBlock, result: ResultBlock };

export function AICopilotEconomicsSession() {
  const { locale } = useI18n(); const c = getAICopilotCaseCopy(locale); const { evidence, hydrated } = useSkalaState(); const graph = useMemo(() => loadGraph(locale), [locale]); const masteryMap = buildMasteryMap(graph.nodes, evidence); const masteryBefore = useMemo(() => Object.fromEntries(aiCopilotEconomicsCase.skills.map((id) => [id, masteryMap[id]?.mastery ?? 0])), [masteryMap]); const [session, setSession] = useState<AICopilotCaseSession | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!hydrated || session) return; const task = window.setTimeout(() => setSession(parseAICopilotCaseSession(window.localStorage.getItem(aiCopilotCaseStorageKey), masteryBefore)), 0); return () => window.clearTimeout(task); }, [hydrated, masteryBefore, session]);
  useEffect(() => { if (session) window.localStorage.setItem(aiCopilotCaseStorageKey, JSON.stringify(session)); }, [session]);
  useEffect(() => { if (session?.currentStage) window.scrollTo({ top: 0, behavior: "smooth" }); }, [session?.currentStage]);
  if (!session) return <div className="learning-loading" />;
  const update = (patch: Partial<AICopilotCaseSession>, advance = false) => setSession((current) => current ? { ...current, ...patch, currentStage: advance ? nextCaseStage(current.currentStage) : current.currentStage, updatedAt: new Date().toISOString() } : current);
  const restart = () => { const fresh = createAICopilotCaseSession(masteryBefore); window.localStorage.setItem(aiCopilotCaseStorageKey, JSON.stringify(fresh)); setSession(fresh); setError(""); };
  const ActiveBlock = registry[session.currentStage]; const stageIndex = caseStages.indexOf(session.currentStage);
  return <div className="case-session page-frame"><header className="case-session-header"><Link href="/cases">{c.meta.back}</Link><div><span>{c.meta.caseCode}</span><strong>{c.meta.stage} {String(stageIndex + 1).padStart(2, "0")} / {String(caseStages.length).padStart(2, "0")}</strong></div><small>{c.meta.progress}</small><button type="button" onClick={restart}>{c.meta.restart}</button></header><div className="learning-progress"><span style={{ width: `${((stageIndex + 1) / caseStages.length) * 100}%` }} /></div><ActiveBlock session={session} update={update} error={error} setError={setError} /></div>;
}
