import type { Locale } from "@/i18n/config";
import { caseDefinitionSchema, type CaseDecision, type CaseDefinition } from "@/lib/cases/schemas";

const l = (es: string, en: string) => ({ "es-CL": es, en });
const metric = (es: string, en: string, value: string, noteEs: string, noteEn: string) => ({ label: l(es, en), value, note: l(noteEs, noteEn) });

const pricingPressure = caseDefinitionSchema.parse({
  id: "case.pricing-pressure", slug: "pricing-pressure", version: "0.1", estimatedMinutes: 16,
  skills: ["pricing-strategy", "elasticity", "switching-costs", "economics.unit-economics", "competitive-advantage"], rubricId: "case.pricing-pressure.v1",
  title: l("Presión sobre el precio", "Pricing under pressure"), subtitle: l("Cuando proteger volumen puede destruir la lógica del negocio.", "When protecting volume can destroy the logic of the business."),
  context: { company: "ClaroOps", role: l("Lideras estrategia comercial y debes recomendar el próximo movimiento de precio.", "You lead commercial strategy and must recommend the next pricing move."), premise: l("Un competidor redujo precios 25%. Ventas quiere igualarlo; Finanzas advierte que el margen no lo resiste.", "A competitor cut prices by 25%. Sales wants to match; Finance warns the margin cannot absorb it.") },
  sections: [
    { id: "market", label: l("Mercado", "Market"), title: l("El ataque", "The attack"), body: l("Un nuevo plan competidor replica las funciones básicas y entra con un precio mucho menor. Aún no tiene integraciones profundas ni soporte local.", "A new competitor plan replicates core features at a much lower price. It still lacks deep integrations and local support."), metrics: [metric("Diferencia de precio", "Price gap", "−25%", "contra ClaroOps", "versus ClaroOps"), metric("Cuentas en riesgo", "Accounts at risk", "18%", "pipeline renovable", "renewal pipeline"), metric("Win rate", "Win rate", "41%", "bajó desde 53%", "down from 53%")] },
    { id: "segments", label: l("Segmentos", "Segments"), title: l("No todos compran lo mismo", "Not everyone buys the same thing"), body: l("Las pymes valoran simplicidad y precio. Enterprise depende de integraciones, cumplimiento y tiempos de respuesta garantizados.", "Small businesses value simplicity and price. Enterprise depends on integrations, compliance and guaranteed response times."), metrics: [metric("Pymes", "SMB", "46%", "del ingreso", "of revenue"), metric("Enterprise", "Enterprise", "54%", "del ingreso", "of revenue"), metric("Retención enterprise", "Enterprise retention", "94%", "últimos 12 meses", "last 12 months")] },
    { id: "economics", label: l("Economía", "Economics"), title: l("El descuento tiene una cola", "The discount has a tail"), body: l("Igualar el precio reduce contribución por cuenta y exige casi duplicar nuevas ventas para sostener el resultado anual.", "Matching price lowers contribution per account and requires nearly doubling new sales to preserve annual results."), metrics: [metric("Margen contribución", "Contribution margin", "58%", "actual", "current"), metric("Con descuento", "After discount", "39%", "sin reducir servicio", "without service cuts"), metric("Breakeven volumen", "Breakeven volume", "+82%", "nuevas cuentas", "new accounts")] },
    { id: "behavior", label: l("Comportamiento", "Behavior"), title: l("La primera señal no es elasticidad", "The first signal is not elasticity"), body: l("En una prueba de cuatro semanas, el descuento elevó demos pero no cierres enterprise. En pymes aumentó conversión y también churn temprano.", "In a four-week test, the discount raised demos but not enterprise closes. In SMB it lifted conversion and also early churn."), metrics: [metric("Demos", "Demos", "+31%", "todas las cuentas", "all accounts"), metric("Cierre enterprise", "Enterprise close", "+2 pp", "muestra pequeña", "small sample"), metric("Churn pyme", "SMB churn", "+7 pp", "a 90 días", "at 90 days")] },
  ],
  newInformation: {
    procurement: { title: l("La amenaza cambia de forma", "The threat changes shape"), body: l("Tres clientes enterprise exigen una opción 15% más barata, pero aceptarían menor soporte y menos integraciones.", "Three enterprise customers demand a 15% cheaper option but would accept less support and fewer integrations."), implication: l("Debes decidir si segmentar la oferta protege valor o sólo desplaza complejidad.", "Decide whether segmenting the offer protects value or merely moves complexity.") },
    retention: { title: l("El volumen era menos durable", "Volume was less durable"), body: l("La mitad de las nuevas pymes atraídas por descuento abandona antes del sexto mes.", "Half of new SMB customers attracted by the discount leave before month six."), implication: l("La adquisición inicial debe releerse junto con retención y economía por cohorte.", "Initial acquisition must be re-read with retention and cohort economics.") },
  }, reviewStatus: "validated",
});

const aiNativeChallenger = caseDefinitionSchema.parse({
  id: "case.ai-native-challenger", slug: "ai-native-challenger", version: "0.1", estimatedMinutes: 18,
  skills: ["competitive-advantage", "ai-distribution-advantage", "ai-data-advantage", "ai-model-commoditization", "organizational-design"], rubricId: "case.ai-native-challenger.v1",
  title: l("El desafiante AI-native", "The AI-native challenger"), subtitle: l("Responder a otra arquitectura sin copiar su superficie.", "Responding to a different architecture without copying its surface."),
  context: { company: "AtlasFlow", role: l("Asesoras al CEO de una plataforma de workflow con diez años de mercado.", "You advise the CEO of a workflow platform with ten years in market."), premise: l("Un competidor AI-native promete ejecutar el trabajo, no sólo organizarlo. Debes decidir dónde responder y qué no copiar.", "An AI-native competitor promises to execute work, not merely organize it. Decide where to respond and what not to copy.") },
  sections: [
    { id: "challenger", label: l("Desafiante", "Challenger"), title: l("Una propuesta distinta", "A different proposition"), body: l("NovaRun automatiza flujos desde lenguaje natural y cobra por resultado. Tiene pocas integraciones, pero mejora rápido con cada implementación.", "NovaRun automates workflows from natural language and charges per outcome. It has few integrations but improves quickly with every deployment."), metrics: [metric("Tiempo a valor", "Time to value", "3 días", "piloto promedio", "average pilot"), metric("Integraciones", "Integrations", "24", "contra 310", "versus 310"), metric("Precio", "Price", "Por outcome", "sin asientos", "no seats")] },
    { id: "incumbent", label: l("AtlasFlow", "AtlasFlow"), title: l("Activos que la UI no muestra", "Assets the UI does not show"), body: l("AtlasFlow está embebida en procesos críticos, tiene distribución por partners y conoce excepciones operativas de 1.400 clientes.", "AtlasFlow is embedded in critical processes, has partner distribution and knows operational exceptions across 1,400 customers."), metrics: [metric("Clientes", "Customers", "1.400", "empresas", "companies"), metric("Partners", "Partners", "86", "implementadores", "implementers"), metric("Datos históricos", "Historical data", "9 años", "eventos de workflow", "workflow events")] },
    { id: "response", label: l("Respuesta", "Response"), title: l("La tentación de copiar", "The temptation to copy"), body: l("Producto propone un copiloto transversal en seis meses. Operaciones advierte que los procesos y permisos actuales no soportan acciones autónomas.", "Product proposes a horizontal copilot in six months. Operations warns current processes and permissions cannot support autonomous actions."), metrics: [metric("Inversión", "Investment", "US$2,4M", "primer año", "year one"), metric("Cobertura", "Coverage", "70%", "workflows objetivo", "target workflows"), metric("Rediseño operativo", "Operating redesign", "No incluido", "en el plan", "in the plan")] },
    { id: "signals", label: l("Señales", "Signals"), title: l("Velocidad no equivale a ventaja", "Speed is not the same as advantage"), body: l("Los pilotos del desafiante son rápidos, pero dos clientes frenaron producción por auditoría y control. Sus usuarios aman la experiencia inicial.", "The challenger's pilots are fast, but two customers paused production over audit and control. Users love the initial experience."), metrics: [metric("Conversión piloto", "Pilot conversion", "64%", "NovaRun", "NovaRun"), metric("Producción", "Production", "37%", "tras auditoría", "after audit"), metric("NPS piloto", "Pilot NPS", "+54", "usuarios finales", "end users")] },
  ],
  newInformation: {
    channel: { title: l("El canal empieza a moverse", "The channel starts moving"), body: l("Doce partners de AtlasFlow piden herramientas para construir agentes propios sobre la plataforma.", "Twelve AtlasFlow partners ask for tools to build their own agents on the platform."), implication: l("Debes valorar si habilitar el ecosistema es una respuesta más durable que copiar una experiencia.", "Assess whether enabling the ecosystem is more durable than copying an experience.") },
    control: { title: l("La autonomía encuentra una frontera", "Autonomy meets a boundary"), body: l("Un regulador exige trazabilidad por decisión automatizada en el principal segmento de AtlasFlow.", "A regulator requires traceability for each automated decision in AtlasFlow's largest segment."), implication: l("La capacidad de control puede convertirse en producto, no sólo en costo de cumplimiento.", "Control capability may become product, not merely compliance cost.") },
  }, reviewStatus: "validated",
});

export type ExpandedCaseConfig = {
  definition: CaseDefinition; code: string;
  decisionLabels: Record<Locale, Record<CaseDecision, string>>;
  markers: Record<Locale, string[]>;
};

export const expandedCases: ExpandedCaseConfig[] = [
  { definition: pricingPressure, code: "001", decisionLabels: { "es-CL": { vendor: "Igualar el precio", build: "Mantener el precio", hybrid: "Segmentar oferta y precio", defer: "Ejecutar una prueba limitada" }, en: { vendor: "Match the price", build: "Hold the price", hybrid: "Segment offer and price", defer: "Run a limited test" } }, markers: { "es-CL": ["segment", "margen", "retención", "elastic", "valor", "cohorte"], en: ["segment", "margin", "retention", "elastic", "value", "cohort"] } },
  { definition: aiNativeChallenger, code: "003", decisionLabels: { "es-CL": { vendor: "Copiar la experiencia", build: "Construir capacidad propia", hybrid: "Activar plataforma y partners", defer: "Observar antes de invertir" }, en: { vendor: "Copy the experience", build: "Build proprietary capability", hybrid: "Activate platform and partners", defer: "Observe before investing" } }, markers: { "es-CL": ["distribución", "datos", "control", "workflow", "ventaja", "partner"], en: ["distribution", "data", "control", "workflow", "advantage", "partner"] } },
];

export function getExpandedCase(slug: string) { return expandedCases.find((item) => item.definition.slug === slug); }
