import type { Locale } from "@/i18n/config";
import { caseDefinitionSchema, type CaseDecision, type CaseDefinition } from "@/lib/cases/schemas";

const l = (es: string, en: string) => ({ "es-CL": es, en });
const metric = (es: string, en: string, value: string, noteEs: string, noteEn: string) => ({ label: l(es, en), value, note: l(noteEs, noteEn) });

const pricingPressure = caseDefinitionSchema.parse({
  id: "case.pricing-pressure", slug: "pricing-pressure", version: "0.1", estimatedMinutes: 16,
  skills: ["pricing-strategy", "elasticity", "switching-costs", "economics.unit-economics", "competitive-advantage"], rubricId: "case.pricing-pressure.v1",
  title: l("Presión sobre los precios", "Pricing under pressure"), subtitle: l("Cuando proteger el volumen puede destruir la lógica del negocio.", "When protecting volume can destroy the logic of the business."),
  context: { company: "ClaroOps", role: l("Lideras la estrategia comercial y debes recomendar la próxima decisión de precios.", "You lead commercial strategy and must recommend the next pricing move."), premise: l("Un competidor redujo sus precios en 25%. Ventas quiere igualar la rebaja; Finanzas advierte que el margen no la soportaría.", "A competitor cut prices by 25%. Sales wants to match; Finance warns the margin cannot absorb it.") },
  sections: [
    { id: "market", label: l("Mercado", "Market"), title: l("El ataque", "The attack"), body: l("Un nuevo plan de la competencia replica las funciones básicas y ofrece un precio mucho menor. Aún carece de integraciones profundas y soporte local.", "A new competitor plan replicates core features at a much lower price. It still lacks deep integrations and local support."), metrics: [metric("Diferencia de precio", "Price gap", "−25%", "frente a ClaroOps", "versus ClaroOps"), metric("Cuentas en riesgo", "Accounts at risk", "18%", "de las renovaciones en curso", "renewal pipeline"), metric("Tasa de cierre", "Win rate", "41%", "antes era 53%", "down from 53%")] },
    { id: "segments", label: l("Segmentos", "Segments"), title: l("No todos compran lo mismo", "Not everyone buys the same thing"), body: l("Las pymes valoran la simplicidad y el precio. Las grandes empresas dependen de integraciones, cumplimiento normativo y tiempos de respuesta garantizados.", "Small businesses value simplicity and price. Enterprise depends on integrations, compliance and guaranteed response times."), metrics: [metric("Pymes", "SMB", "46%", "de los ingresos", "of revenue"), metric("Grandes empresas", "Enterprise", "54%", "de los ingresos", "of revenue"), metric("Retención en grandes empresas", "Enterprise retention", "94%", "últimos 12 meses", "last 12 months")] },
    { id: "economics", label: l("Economía", "Economics"), title: l("El descuento tiene efectos duraderos", "The discount has a tail"), body: l("Igualar el precio reduce el margen de contribución por cuenta y obliga a aumentar las nuevas ventas en 82% para sostener el resultado anual.", "Matching price lowers contribution per account and requires nearly doubling new sales to preserve annual results."), metrics: [metric("Margen de contribución", "Contribution margin", "58%", "actual", "current"), metric("Con descuento", "After discount", "39%", "sin reducir el servicio", "without service cuts"), metric("Volumen de equilibrio", "Breakeven volume", "+82%", "en cuentas nuevas", "new accounts")] },
    { id: "behavior", label: l("Comportamiento", "Behavior"), title: l("La primera señal no basta para medir elasticidad", "The first signal is not elasticity"), body: l("En una prueba de cuatro semanas, el descuento aumentó las demostraciones, pero no los cierres con grandes empresas. Entre las pymes mejoró la conversión, aunque también aumentó el abandono temprano.", "In a four-week test, the discount raised demos but not enterprise closes. In SMB it lifted conversion and also early churn."), metrics: [metric("Demostraciones", "Demos", "+31%", "en todas las cuentas", "all accounts"), metric("Cierre en grandes empresas", "Enterprise close", "+2 p. p.", "muestra pequeña", "small sample"), metric("Abandono en pymes", "SMB churn", "+7 p. p.", "a 90 días", "at 90 days")] },
  ],
  newInformation: {
    procurement: { title: l("La amenaza cambia de forma", "The threat changes shape"), body: l("Tres clientes grandes exigen una opción 15% más barata, pero aceptarían menos soporte y menos integraciones.", "Three enterprise customers demand a 15% cheaper option but would accept less support and fewer integrations."), implication: l("Debes decidir si segmentar la oferta protege el valor o sólo traslada la complejidad a otra parte del negocio.", "Decide whether segmenting the offer protects value or merely moves complexity.") },
    retention: { title: l("El volumen era menos estable", "Volume was less durable"), body: l("La mitad de las nuevas pymes atraídas por el descuento abandona el servicio antes del sexto mes.", "Half of new SMB customers attracted by the discount leave before month six."), implication: l("Debes analizar la adquisición inicial junto con la retención y la rentabilidad de cada cohorte.", "Initial acquisition must be re-read with retention and cohort economics.") },
  }, reviewStatus: "validated",
});

const aiNativeChallenger = caseDefinitionSchema.parse({
  id: "case.ai-native-challenger", slug: "ai-native-challenger", version: "0.1", estimatedMinutes: 18,
  skills: ["competitive-advantage", "ai-distribution-advantage", "ai-data-advantage", "ai-model-commoditization", "organizational-design"], rubricId: "case.ai-native-challenger.v1",
  title: l("El competidor nativo en IA", "The AI-native challenger"), subtitle: l("Cómo responder a un modelo distinto sin limitarse a copiar lo visible.", "Responding to a different architecture without copying its surface."),
  context: { company: "AtlasFlow", role: l("Asesoras al CEO de una plataforma de gestión de flujos de trabajo con diez años en el mercado.", "You advise the CEO of a workflow platform with ten years in market."), premise: l("Un competidor nativo en IA promete ejecutar el trabajo, no sólo organizarlo. Debes decidir dónde responder y qué no conviene copiar.", "An AI-native competitor promises to execute work, not merely organize it. Decide where to respond and what not to copy.") },
  sections: [
    { id: "challenger", label: l("Competidor", "Challenger"), title: l("Una propuesta distinta", "A different proposition"), body: l("NovaRun automatiza flujos a partir de instrucciones en lenguaje natural y cobra por resultado. Tiene pocas integraciones, pero mejora rápidamente con cada implementación.", "NovaRun automates workflows from natural language and charges per outcome. It has few integrations but improves quickly with every deployment."), metrics: [metric("Tiempo hasta generar valor", "Time to value", "3 días", "piloto promedio", "average pilot"), metric("Integraciones", "Integrations", "24", "frente a 310", "versus 310"), metric("Precio", "Price", "Por resultado", "sin cobro por usuario", "no seats")] },
    { id: "incumbent", label: l("AtlasFlow", "AtlasFlow"), title: l("Activos que la interfaz no muestra", "Assets the UI does not show"), body: l("AtlasFlow está integrada en procesos críticos, cuenta con una red de socios comerciales y conoce las excepciones operativas de 1.400 clientes.", "AtlasFlow is embedded in critical processes, has partner distribution and knows operational exceptions across 1,400 customers."), metrics: [metric("Clientes", "Customers", "1.400", "empresas", "companies"), metric("Socios", "Partners", "86", "implementadores", "implementers"), metric("Datos históricos", "Historical data", "9 años", "de eventos operativos", "workflow events")] },
    { id: "response", label: l("Respuesta", "Response"), title: l("La tentación de copiar", "The temptation to copy"), body: l("El área de Producto propone lanzar un copiloto transversal en seis meses. Operaciones advierte que los procesos y permisos actuales no están preparados para acciones autónomas.", "Product proposes a horizontal copilot in six months. Operations warns current processes and permissions cannot support autonomous actions."), metrics: [metric("Inversión", "Investment", "US$2,4M", "primer año", "year one"), metric("Cobertura", "Coverage", "70%", "de los flujos objetivo", "target workflows"), metric("Rediseño operativo", "Operating redesign", "Fuera del plan", "por ahora", "in the plan")] },
    { id: "signals", label: l("Señales", "Signals"), title: l("La velocidad no equivale a una ventaja", "Speed is not the same as advantage"), body: l("Los pilotos del competidor avanzan rápido, pero dos clientes detuvieron la puesta en producción por problemas de auditoría y control. Aun así, los usuarios valoran mucho la experiencia inicial.", "The challenger's pilots are fast, but two customers paused production over audit and control. Users love the initial experience."), metrics: [metric("Conversión de pilotos", "Pilot conversion", "64%", "NovaRun", "NovaRun"), metric("Puesta en producción", "Production", "37%", "después de auditoría", "after audit"), metric("NPS del piloto", "Pilot NPS", "+54", "usuarios finales", "end users")] },
  ],
  newInformation: {
    channel: { title: l("El canal comienza a reaccionar", "The channel starts moving"), body: l("Doce socios de AtlasFlow piden herramientas para construir sus propios agentes sobre la plataforma.", "Twelve AtlasFlow partners ask for tools to build their own agents on the platform."), implication: l("Debes evaluar si fortalecer el ecosistema ofrece una respuesta más duradera que copiar la experiencia del competidor.", "Assess whether enabling the ecosystem is more durable than copying an experience.") },
    control: { title: l("La autonomía encuentra un límite", "Autonomy meets a boundary"), body: l("Un regulador exige trazabilidad para cada decisión automatizada en el principal segmento de AtlasFlow.", "A regulator requires traceability for each automated decision in AtlasFlow's largest segment."), implication: l("La capacidad de control puede transformarse en una ventaja de producto, no sólo en un costo de cumplimiento.", "Control capability may become product, not merely compliance cost.") },
  }, reviewStatus: "validated",
});

export type ExpandedCaseConfig = {
  definition: CaseDefinition; code: string;
  decisionLabels: Record<Locale, Record<CaseDecision, string>>;
  markers: Record<Locale, string[]>;
};

export const expandedCases: ExpandedCaseConfig[] = [
  { definition: pricingPressure, code: "001", decisionLabels: { "es-CL": { vendor: "Igualar el precio", build: "Mantener el precio", hybrid: "Segmentar oferta y precio", defer: "Ejecutar una prueba limitada" }, en: { vendor: "Match the price", build: "Hold the price", hybrid: "Segment offer and price", defer: "Run a limited test" } }, markers: { "es-CL": ["segment", "margen", "retención", "elastic", "valor", "cohorte"], en: ["segment", "margin", "retention", "elastic", "value", "cohort"] } },
  { definition: aiNativeChallenger, code: "003", decisionLabels: { "es-CL": { vendor: "Copiar la experiencia", build: "Desarrollar una capacidad propia", hybrid: "Fortalecer la plataforma y sus socios", defer: "Observar antes de invertir" }, en: { vendor: "Copy the experience", build: "Build proprietary capability", hybrid: "Activate platform and partners", defer: "Observe before investing" } }, markers: { "es-CL": ["distribución", "datos", "control", "flujo", "ventaja", "socio"], en: ["distribution", "data", "control", "workflow", "advantage", "partner"] } },
];

export function getExpandedCase(slug: string) { return expandedCases.find((item) => item.definition.slug === slug); }
