"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowIcon, SparkIcon } from "@/components/layout/icons";
import { economicsUnit } from "@/content/programs/business-core";
import { st, survia, surviaCopy, surviaDimensionNames } from "@/content/programs/survia";
import { seedEvidence } from "@/content/mastery/seed";
import { useI18n } from "@/i18n/provider";
import { evaluateSurvia } from "@/lib/ai/survia";
import { loadGraph } from "@/lib/content/load-content";
import { buildMasteryMap } from "@/lib/demo/state";
import { calculateMastery, type EvidenceEvent } from "@/lib/mastery/engine";
import { createSurviaSession, nextSurviaStage, parseSurviaSession, surviaStages, surviaStorageKey, type SurviaSession } from "@/lib/programs/checkpoint-session";
import { useSkalaState } from "@/lib/state/provider";

function Metrics({ items }: { items: [Record<"es-CL" | "en", string>, string][] }) { const { locale } = useI18n(); return <div className="survia-metrics">{items.map(([label, value]) => <div key={label.en}><span>{label[locale]}</span><strong>{value}</strong></div>)}</div>; }
function TextForm({ name, value, label, cta, error, onSubmit }: { name: string; value?: string; label: string; cta: string; error: string; onSubmit: (value: string) => void }) { const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); onSubmit(new FormData(event.currentTarget).get(name)?.toString().trim() ?? ""); }; return <form onSubmit={submit}><label>{label}<textarea rows={6} name={name} defaultValue={value} /></label>{error && <p className="learning-error">{error}</p>}<button className="primary-action case-action">{cta}<ArrowIcon /></button></form>; }

export function SurviaCheckpoint() {
  const { locale } = useI18n(); const copy = surviaCopy[locale]; const { evidence, hydrated, addEvidence, completeCheckpoint, checkpointCompletions } = useSkalaState();
  const graph = useMemo(() => loadGraph(locale), [locale]); const mastery = buildMasteryMap(graph.nodes, evidence); const tracked = economicsUnit.checkpoint!.evidenceSkillIds; const masteryBefore = Object.fromEntries(tracked.map((id) => [id, mastery[id]?.mastery ?? 0]));
  const [session, setSession] = useState<SurviaSession | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!hydrated || session) return; const task = window.setTimeout(() => setSession(parseSurviaSession(window.localStorage.getItem(surviaStorageKey), masteryBefore)), 0); return () => window.clearTimeout(task); }, [hydrated, masteryBefore, session]);
  useEffect(() => { if (session) window.localStorage.setItem(surviaStorageKey, JSON.stringify(session)); }, [session]);
  if (!session) return <div className="learning-loading" />;
  const index = surviaStages.indexOf(session.stage); const update = (patch: Partial<SurviaSession>, advance = false) => setSession((current) => current ? { ...current, ...patch, stage: advance ? nextSurviaStage(current.stage) : current.stage, updatedAt: new Date().toISOString() } : current);
  const restart = () => { window.localStorage.removeItem(surviaStorageKey); setError(""); setSession(createSurviaSession(masteryBefore)); };
  const submitLong = (field: keyof SurviaSession, value: string) => { if (value.length < 80) return setError(copy.responseLong); setError(""); update({ [field]: value }, true); };
  const finish = async (value: string) => {
    if (value.length < 80) return setError(copy.responseLong); if (session.finalDecision === undefined) return setError(copy.selectDecision); if ((session.uncertainty?.length ?? 0) < 30) return setError(copy.responseLong);
    const evaluation = await evaluateSurvia({ locale, initialDecision: session.initialDecision!, finalDecision: session.finalDecision, economicsResponse: session.economicsResponse!, initialRationale: session.initialRationale!, competitorResponse: session.competitorResponse!, incentiveResponse: session.incentiveResponse!, finalRecommendation: value, uncertainty: session.uncertainty! });
    const occurredAt = new Date().toISOString(); const dimensionKeys = Object.keys(evaluation.dimensions) as Array<keyof typeof evaluation.dimensions>; const events: EvidenceEvent[] = tracked.map((skillId, skillIndex) => { const dimension = dimensionKeys[skillIndex % dimensionKeys.length]; const performance = evaluation.dimensions[dimension]; return { id: `${session.sessionId}:${skillId}`, skillId, type: "application" as const, performance, occurredAt: new Date(Date.now() + skillIndex).toISOString(), sourceId: session.sessionId, dimensions: { [dimension]: performance }, metadata: { programId: "business-core", unitId: economicsUnit.id, checkpointId: survia.id, evaluatorVersion: evaluation.evaluatorVersion } }; });
    const masteryAfter = Object.fromEntries(tracked.map((id) => [id, calculateMastery(id, [...seedEvidence, ...evidence, ...events]).mastery]));
    addEvidence(events); completeCheckpoint({ checkpointId: survia.id, sessionId: session.sessionId, completedAt: occurredAt, version: survia.version, overallPerformance: evaluation.overallPerformance }); setError(""); update({ finalRecommendation: value, evaluation, masteryAfter, completedAt: occurredAt }, true);
  };
  const chooseInitial = (value: string) => { if (session.initialDecision === undefined) return setError(copy.selectDecision); if (value.length < 80) return setError(copy.responseLong); setError(""); update({ initialRationale: value }, true); };
  return <div className="case-session survia-session page-frame"><header className="case-session-header"><Link href={`/programs/business-core/units/${economicsUnit.id}`}>{copy.back}</Link><div><span>{copy.checkpoint}</span><strong>{st(survia.title, locale)}</strong></div><small>{copy.time}</small><button type="button" onClick={restart}>{copy.restart}</button></header><div className="survia-stage-map">{survia.stages.map((stage, stageIndex) => <span className={stageIndex < index ? "complete" : stageIndex === index ? "active" : ""} key={stage[locale]}><i /><small>{st(stage, locale)}</small></span>)}</div>
    {session.stage === "market" && <section className="case-workspace-block survia-block"><p className="section-label"><SparkIcon />{copy.evidence} · 01</p><h1>{st(survia.market.title, locale)}</h1><p className="case-lede">{st(survia.market.body, locale)}</p><Metrics items={survia.market.metrics} /><h2>{st(survia.market.prompt, locale)}</h2><div className="survia-question-grid">{survia.market.questions.map((question, questionIndex) => <button type="button" className={session.selectedQuestions.includes(questionIndex) ? "selected" : ""} onClick={() => update({ selectedQuestions: session.selectedQuestions.includes(questionIndex) ? session.selectedQuestions.filter((item) => item !== questionIndex) : [...session.selectedQuestions, questionIndex].slice(-3) })} key={question[locale]}><span>0{questionIndex + 1}</span>{st(question, locale)}</button>)}</div><p className="case-requirement">{session.selectedQuestions.length} / 3 {copy.selected}</p>{error && <p className="learning-error">{error}</p>}<button className="primary-action case-action" onClick={() => session.selectedQuestions.length === 3 ? (setError(""), update({}, true)) : setError(copy.selectThree)}>{copy.continue}<ArrowIcon /></button></section>}
    {session.stage === "economics" && <section className="case-workspace-block survia-block"><p className="section-label"><SparkIcon />{copy.evidence} · 02</p><h1>{st(survia.economics.title, locale)}</h1><p className="case-lede">{st(survia.economics.body, locale)}</p><Metrics items={survia.economics.metrics} /><TextForm name="economics" value={session.economicsResponse} label={st(survia.economics.prompt, locale)} cta={copy.continue} error={error} onSubmit={(value) => submitLong("economicsResponse", value)} /></section>}
    {session.stage === "initial" && <section className="case-form-block survia-block"><p className="section-label"><SparkIcon />{copy.checkpoint}</p><h1>{st(survia.initial.title, locale)}</h1><div className="case-decision-picker survia-decisions">{survia.choices.map((choice, choiceIndex) => <button type="button" className={session.initialDecision === choiceIndex ? "selected" : ""} onClick={() => update({ initialDecision: choiceIndex })} key={choice[locale]}>{st(choice, locale)}</button>)}</div><TextForm name="initial" value={session.initialRationale} label={st(survia.initial.prompt, locale)} cta={copy.submit} error={error} onSubmit={chooseInitial} /></section>}
    {session.stage === "competitor" && <section className="case-new-info survia-block"><p className="section-label"><SparkIcon />{copy.evidence} · 03</p><h1>{st(survia.competitor.title, locale)}</h1><article><span>03</span><p>{st(survia.competitor.body, locale)}</p></article><TextForm name="competitor" value={session.competitorResponse} label={st(survia.competitor.prompt, locale)} cta={copy.revise} error={error} onSubmit={(value) => submitLong("competitorResponse", value)} /></section>}
    {session.stage === "incentive" && <section className="case-new-info survia-block"><p className="section-label"><SparkIcon />{copy.evidence} · 04</p><h1>{st(survia.incentive.title, locale)}</h1><article><span>04</span><p>{st(survia.incentive.body, locale)}</p></article><TextForm name="incentive" value={session.incentiveResponse} label={st(survia.incentive.prompt, locale)} cta={copy.continue} error={error} onSubmit={(value) => submitLong("incentiveResponse", value)} /></section>}
    {session.stage === "final" && <section className="case-form-block survia-block"><p className="section-label"><SparkIcon />{copy.checkpoint}</p><h1>{st(survia.final.title, locale)}</h1><div className="case-decision-picker survia-decisions">{survia.choices.map((choice, choiceIndex) => <button type="button" className={session.finalDecision === choiceIndex ? "selected" : ""} onClick={() => update({ finalDecision: choiceIndex })} key={choice[locale]}>{st(choice, locale)}</button>)}</div><label className="survia-uncertainty">{st(survia.final.uncertainty, locale)}<textarea rows={3} value={session.uncertainty ?? ""} onChange={(event) => update({ uncertainty: event.target.value })} /></label><TextForm name="final" value={session.finalRecommendation} label={st(survia.final.prompt, locale)} cta={copy.finish} error={error} onSubmit={finish} /></section>}
    {session.stage === "result" && session.evaluation && <section className="case-result survia-block"><p className="section-label"><SparkIcon />{copy.result}</p><h1>{copy.status}</h1><div className="case-overall"><strong>{Math.round(session.evaluation.overallPerformance * 100)}</strong><span>{copy.evaluator}</span></div><p className="eyebrow">{copy.dimensions}</p><div className="case-dimension-grid">{Object.entries(session.evaluation.dimensions).map(([dimension, score]) => <article key={dimension}><div><span>{st(surviaDimensionNames[dimension as keyof typeof surviaDimensionNames], locale)}</span><strong>{Math.round(score * 100)}</strong></div><i><b style={{ width: `${score * 100}%` }} /></i></article>)}</div><div className="case-feedback"><article><span>{copy.strength}</span><p>{session.evaluation.strength[locale]}</p></article><article><span>{copy.improvement}</span><p>{session.evaluation.improvement[locale]}</p></article></div><p className="eyebrow survia-mastery-label">{copy.mastery}</p><div className="case-evidence-result">{tracked.map((id) => <div key={id}><span>{graph.nodes.find((node) => node.id === id)?.title}</span><strong>{session.masteryBefore[id]}<i>→</i>{session.masteryAfter?.[id]}</strong></div>)}</div><div className="case-result-actions"><Link className="primary-action" href={`/skala?focus=pricing-strategy&updated=1`}>{copy.map}<ArrowIcon /></Link><Link className="text-action" href={`/programs/business-core/units/${economicsUnit.id}`}>{copy.unit}<ArrowIcon /></Link></div>{checkpointCompletions.some((item) => item.sessionId === session.sessionId) && <span className="unit-completion-stamp">✓</span>}</section>}
  </div>;
}
